import classes.Customer;
import classes.Gender;

/**
 * Created by Elimane on Sep, 2018, at 14:07
 */
public class HashCodeTest {

    public static void main(String[] args)
    {
        /**
        *
        *@Understanding_How_hashCode()_Works
        * Simply put, hashCode() returns an integer value, generated by a hashing algorithm.
        * Objects that are equal (according to their equals()) must return the same hash code.
        * It’s not required for different objects to return different hash codes.
        * The general contract of hashCode() states:Whenever it is invoked on the same object
        * more than once during an execution of a Java application, hashCode() must consistently
        * return the same value, provided no information used in equals comparisons on the object is modified.
        * This value needs not remain consistent from one execution of an application to another execution of the
        * same applicationIf two objects are equal according to the equals(Object) method,
        * then calling the hashCode() method on each of the two objects must produce the same valueIt is not
        * required that if two objects are unequal according to the equals(java.lang.Object) method,
        * then calling the hashCode method on each of the two objects must produce distinct integer results. However,
        * developers should be aware that producing distinct integer results for unequal objects improves the performance of hash tables
        *
        * */

        Customer c1 = new Customer("1","John","McCall",true, Gender.MALE);
        Customer c2 = new Customer("2","Olivia","Maxwell",true, Gender.FEMALE);

        System.out.println(c1.hashCode());
        System.out.println(c2.hashCode());


    }
}
